export const GETTING_DATA_HAS_ERROR = 'GET_DATA_HAS_ERROR'
export const DATA_IS_LOADING = 'DATA_IS_LOADING'
export const GETTING_DATA_HAS_SUCCESS = 'GET_DATA_HAS_SUCCESS'
export const FETCH_DATA = 'FETCH_DATA'
